### ISSUE TITLE
Disable the GIF download, not just playing. And please make the documentation state what it does in the 1st paragraph.

### ISSUE THREAD

**Issue by bruceleerabbit** [M-Reimer/toggleanigif#15]
The description of this plugin makes no statement about whether GIFs are downloaded -- not in this repo and not on the Mozilla page. This is important. For people on limited connections it’s important because the plugin is useless if it does not prevent the download.

I took these steps to disable images:

`about:config` » `permissions.default.image` » `1`→`2`

Strangely, that does not work for animated GIFs.. wtf?  So I took this step:

`about:config` » `image.animation_mode` » (`normal` → `none`)

Also useless.. that still fetches the GIF thus wasting limited bandwidth. If your plugin is merely affecting the same setting, then it has the same problem. So I am reporting 2 bugs:

1. The docs don’t say whether GIFs are fetched
2. If the plugin only controls playing and fetches GIFs either way, then please improve the plugin so when playing is disabled animated GIFs are not fetched.

**Comment by M-Reimer** [comment]
The add-on is certainly not useless. Many people are using it because they don't like animated images and want to be able to disable the animation with just one click.

The Add-on is not a filter and does not prevent anything from loading. Actually I thought that the wording "Disables or enables **the animation of images** (usually animateg GIF)." already tells this.

**Comment by M-Reimer** [comment]
Wording on the AMO page improved and type corrected.
