### ISSUE TITLE
Doesn't toggle and hover gif don't animate

### ISSUE THREAD

**Issue by donkoch** [M-Reimer/toggleanigif#19]
Once you freeze a gif, you can't unfreeze it (toggle doesn't). It also seems to freezes all the gifs on the page.

Hover to animate gifs, like on Tumblr, won't animate if this extension is merely enable.
https://www.tumblr.com/dandelionandkrindle/758127784587640832/the-harbinger-of-the-kingdom-that-was

Firefox 127.0.2 on linux (fedora 40).

**Comment by M-Reimer** [comment]
Will try later.

But how did you attempt to "freeze"? If you want to freeze individual images, you have to enable the context menu item in the Add-on settings.

**Comment by donkoch** [comment]
It is enabled. It shows up in the menu.
It seemed to work until I added the shortcut (maybe coincidental). That seemed to work, too.
Then all gif animation failed, even after removing the shortcut.

**Comment by donkoch** [comment]
Just tried an uninstall/reinstall and it seems to be happy, again. I suspect something is getting cached that breaks it. Will update after some more testing.

**Comment by M-Reimer** [comment]
I'm somewhat limited to what Firefox allows me to do.
The "global toggle" DOES require a page reload so you see the effect. That's how Firefox is programmed internally and that's why you can toggle an auto page reload in the settings.
The "freeze" feature was added as an optional addition as it somewhat fits with the global toggle feature. It can be used completely independent of the global toggle and also works if you don't use the toolbar button. It is disabled by default as interacting with the website requires full page content access which I don't want to request by default if a user doesn't actually need this feature. Technically it creates a "screenshot" of the image area and replaces the animated image with the screenshot. That's also why a page reload is needed to "unfreeze" as the former image information is lost in this process.

**Comment by M-Reimer** [comment]
Any news?

**Comment by donkoch** [comment]
Haven't seen a non-hover gif in a while. Had to do an uninstall-reinstall to fix it from before.

**Comment by M-Reimer** [comment]
So I guess I can close the issue for now?

**Comment by donkoch** [comment]
Haven't seen a non-hover gif in a while. Had to do an uninstall-reinstall to fix it from before.

**Comment by donkoch** [comment]
Found some GIFs. Now it won't freeze them. I give up. Uninstalling as it is totally useles.

**Comment by M-Reimer** [comment]
Actually I likely just found what your actual problem is.
This "tumblr" page does not actually use regular image sources but image sets. I want to try something tomorrow.

**Comment by donkoch** [comment]
OK. I will await a resolution and try again. Thanks.

**Comment by M-Reimer** [comment]
New version is on its way. For me every single image on tumblr freezes with this change.

Edit: And it is on AMO already. Please tell me if this fixes your problem.
