### ISSUE TITLE
Toggle animated gif

### ISSUE THREAD

**Issue by IoanPaleru** [M-Reimer/toggleanigif#6]
Hi. Toggle animated gif is a great add-on and works really well in firefox, but could you please include an option in the settings to put a small play icon on paused gifs so that people can distinguish gifs from other jpg images on a webpage, and either go into the settings to reenable gif playback, or just click on the icon on a gif to play or pause that individual gif? That would be a great feature that would make toggle animated gif even better, so it would be great if you could include it in the next version. Thanks, and have a great day.

**Comment by M-Reimer** [comment]
All my Add-on does is toggling a Firefox built-in setting. It doesn't interfere in the GIF files and image embeds in any way.

And as animated GIFs get more and more unpopular and replaced by real videos (<video> tag) it is also not really worth it to waste too much time in this.

The best (in theory) way to make the animated GIF files a bit more user friendly would be to transcode them dynamically from animated GIF into some kind of video format to get them loaded with the <video> tag instead of <img>. If this would be possible, then the Firefox default playback controls could be enabled.

But that's all out of scope for a simple "toggle animated gif" Add-on.

**Comment by IoanPaleru** [comment]
Ok, thanks a lot for the great information and add-on.
